import type { Metadata } from 'next'
import './globals.css'
import AppProvider from '@/components/providers'
import NextAuthSessionProvider from '@/components/providers/auth.provider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<AppProvider>
					<NextAuthSessionProvider>
						{children as JSX.Element}
					</NextAuthSessionProvider>
				</AppProvider>
			</body>
		</html>
	)
}
